### ISSUE TITLE
quick deploy - postdeploy script fails

### ISSUE THREAD

**Issue by bruced** [muenzpraeger/blog-wordpress-heroku#1]
> wp core install --skip-email '--title=WordPress on Heroku' '--admin_user=admin' '--admin_password=maverick101' '--admin_email=bruce@visioneeringsystems.com.au' '--url=http://example.herokuapp.com/'

PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /app/wordpress/wp-includes/load.php:317

Stack trace:

#0 /app/vendor/wp-cli/wp-cli/php/utils-wp.php(22): wp_debug_mode()

#1 /app/vendor/wp-cli/wp-cli/php/wp-settings-cli.php(59): WP_CLI\Utils\wp_debug_mode()

#2 /app/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(807): require('/app/vendor/wp-...')

#3 /app/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(755): WP_CLI\Runner->load_wordpress()

#4 /app/vendor/wp-cli/wp-cli/php/wp-cli.php(21): WP_CLI\Runner->start()

#5 /app/vendor/wp-cli/wp-cli/php/boot-fs.php(17): include('/app/vendor/wp-...')

#6 {main}

  thrown in /app/wordpress/wp-includes/load.php on line 317

[37;41mScript wp core install --skip-email handling the wordpress-setup-core-install event returned with error code 255[39;49m

**Comment by bruced** [comment]
BTW This is brilliant work anyway
Thanks

**Comment by muenzpraeger** [comment]
Fixed with this [commit](https://github.com/muenzpraeger/blog-wordpress-heroku/commit/4bee5c31554ce6a04304d07123b0440e900c9d3a) - enjoy!
